[package]
name = "hyttpd"
version = "0.1.1"
authors = ["Jashank Jeremy <jashank@rulingia.com>"]

[dependencies]
hyper = "*"
chrono = "*"

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy"